name: Update Pip Import
on:
  push:
    branches: ['main']
    paths:
      - 'src/**'
      - '!src/docs/**'
      - '!src/*.md'
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'src/**'
      - '!src/docs/**'
      - '!src/*.md'
jobs:
  get_files:
    runs-on: ubuntu-latest
    outputs:
      files_output: ${{ steps.check_files.outputs.files }}
      pip_files_output: ${{ steps.check_pip_files.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print repository name
        run: echo "Running in repository $GITHUB_REPOSITORY"
      - name: Check for new files
        id: check_files
        run: |
          git fetch --depth=1 origin main
          files=$(git diff --name-only HEAD..origin/main src/)
          if [[ -z "$files" ]]; then
            echo "No new files"
          else
            echo "New files:"
            echo "$files"
            new_files=()
            for file in $files; do
               filename=$(basename "$file")
               filename=$(echo "$filename" | sed 's/\.py$//')
               new_files+=("$filename")
            done
            echo "{files}={$new_files}" >> $GITHUB_OUTPUT
           fi
      - name: Check for new files in pipImport.py
        id: check_pip_files
        run: |
           src_files=$(grep -rl --include='*.py' '' src/)
           filenames=()
           for file in $src_files; do
              filename=$(basename "$file")
              filename=$(echo "$filename" | sed 's/\.py$//')
              filenames+=("$filename")
           done
           echo "${filenames[@]}"  
           pip_files=$(grep -oP "(?<=from\s)\w+" pipImport.py)
           missing=()
           for item in "${filenames[@]}"; do
              if ! [[ "${pip_files[*]}" =~ "${item}" ]]; then
                missing+=("$item")
              fi
           done
           echo "Missing elements: ${missing[@]}"
           if [[ -z "$missing" ]]; then
             echo "No new files"
           else
             echo "$missing"
             echo "files=$missing" >> "$GITHUB_OUTPUT"
           fi
  update:
    runs-on: ubuntu-latest
    needs: get_files
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: update pipImport file
        env:
          OUTPUT1: ${{needs.get_files.outputs.files_output}}
          OUTPUT2: ${{needs.get_files.outputs.pip_files_output}}
        run: |
          src_files=$OUTPUT1
          pip_files=$OUTPUT2
          for file in $pip_files; do
            if ! grep -q "$file" pipImport.py; then
               sed -i "/^def help():.*/i with httpimport.remote_repo(['${file}'], url):\n    from ${file} import *\n" pipImport.py            
            fi
          done
          
      - name: Check if file has been modified
        run: |
            if [[ -z $(git diff pipImport.py) ]]; then
              echo "No changes detected in pipImport.py"
              exit 0
            fi
      - name: Commit file
        run: |
          git config --local user.name  ${{ github.actor }}
          git add pipImport.py
          git commit -m "Update pipImport.py file"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
   
